/*
 * book.h
 *
 *  Created on: May 26, 2013
 *      Author: Vijaywargi
 */

#ifndef BOOK_H_
#define BOOK_H_

#include "author.h"

class Book:public Author
{
	string name;
	double price;
	int qtyInStock;
	Author author;

public:
	Book(string name, Author author, double price, int qtyInStock=0);
	const Author& getAuthor() const;
	const string& getName() const;		// why reference here ? (generated by getters)
	double getPrice() const;
	void setPrice(double price);
	int getQtyInStock() const;
	void setQtyInStock(int qtyInStock);

};


#endif /* BOOK_H_ */
